### ISSUE TITLE
Create metadata tags for raw.data outputs

### ISSUE THREAD

**Issue by nish-kishore** [nish-kishore/sirfunctions#16]
`raw.data` currently is a list of objects in R, some of which are tabular but others may be strings or event spatial objects. We need to add a new object in this list called `metadata` which includes: 

NOTE: times need to be when processes are completed not started

raw.data$metadata$download_time
raw.data$metadata$processed_time
raw.data$metadata$user
raw.data$metadata$most_recent_pos
raw.data$metadata$most_recent_afp
raw.data$metadata$most_recent_env
raw.data$metadata$most_recent_sia

**Comment by Heaghneyn** [comment]
adding a few additional metadata elements

raw.data$metadata$most_recent_pos_loc
raw.data$metadata$most_recent_afp_loc
raw.data$metadata$most_recent_es_loc
raw.data$metadata$most_recent_sia_code
raw.data$metadata$most_recent_sia_loc

**Comment by Heaghneyn** [comment]
raw.data$metadata$most_recent_sia_vax
