### ISSUE TITLE
Add metadata tags to figures and tables

### ISSUE THREAD

**Issue by nish-kishore** [nish-kishore/sirfunctions#29]
- [x] input: figure or table, raw.data 
- [x] checks to see if input is figure or table 
- [x] adds appropriate caption and returns figure or table

**Comment by Heaghneyn** [comment]
- [ ] determine if a caption already exists on figure/table

**Comment by Heaghneyn** [comment]
having an issue with certain figures where functions exist that include ggsaves so make it hard to apply the function. function works for individual figures tho

trying to finalize table portion of function
