### ISSUE TITLE
Desk review code modularization - data loading and preparation

### ISSUE THREAD

**Issue by mcuadera** [nish-kishore/sirfunctions#59]
Create `init_dr()` function that creates a snapshot of the dataset used for a desk review. This will require the following:

1. Create a copy in EDAV of the dataset used
2. Create a metadata text file containing information such as: location of dataset, last updated, where the script of the desk review is located
3. Perform simple data cleaning, including the reduction of columns that are never used in the desk review. Still needs thought on whether this should be an explicit list by the user, or if this should be done automatically.

**Comment by nish-kishore** [comment]
**Initiate Desk Review**

- [ ] generate_data(): either pulls data from EDAV or specified location of rds
- [ ] update_data()
- [ ] freeze_data()
- [ ] Set location of local "Desk Reviews" folder 
- [ ] Asks for country / year and creates folder hierarchy 
- [ ] Set folder structure for "Desk Reviews" folder; create local folder structure for country / year -> figures, errors, data, parameters file to keep track of absolute folder references 
- [ ] Asks for location of `sg-desk-reviews` repository 
- [ ] In repo it creates country / year organization, copies master DR template, renames it and puts it in the folder, copies figure creation scripts and puts it in `src` in country specific 
- [ ] Runs country / year script -> produces errors log -> produces key figure output 

**User Workflow**

1. Run `init_dr()` -> asks for country, year, repo location, local folder location, generate_data()
2. init_dr() -> creates local folder hierarchy, creates all global reference
3. init_dr() -> copies template into sub-folder, copies src into sub-folder 
4. init_dr() -> sources src in sub-folder, sources template in sub-folder 
5. template contains calls to global references which show where the output folders are located 
6. User has figures and error log locally, begins working in script
7. At the end user syncs repository 
8. On restart, user provides all initial parameter and can restart

**Comment by mcuadera** [comment]
@nish-kishore Regarding setting the location of the desk review folder. Could we just let the user instead set this using `setwd()`?
