### ISSUE TITLE
Bad data value not being computed

### ISSUE THREAD

**Issue by lizkrowlucal** [nish-kishore/sirfunctions#63]
stool.data1 is created as a clone of stool.data prior to the modifications in stool.data from the bad.data input.

My bad.

Line 276 needs to be moved to after line 299

Trying to explain more... 
Line 276 clones stool.data into stool.data1, but then the 279-299 pushes the changes from function input for bad.data onto stool.data. BUT all of the subsequent calculations use stool.data1

**Comment by mcuadera** [comment]
Made the changes
